# Generated by Django 4.0.5 on 2022-06-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='time',
        ),
    ]
