# Generated by Django 4.0.5 on 2022-06-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_information_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('message', models.CharField(max_length=800)),
                ('phone', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('country', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
